version: "3"

services:
  server1:
    build:
      context: .
      dockerfile: services/server1/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - "./:/code/"
    container_name: server1
    networks:
      - server-network
    
  server2:
    build:
      context: .
      dockerfile: services/server2/Dockerfile
    ports:
      - "8001:8000"
    volumes:
      - "./:/code/"
    container_name: server2
    networks:
      - server-network

  server3:
    build:
      context: .
      dockerfile: services/server3/Dockerfile
    ports:
      - "8002:8000"
    volumes:
      - "./:/code/"
    container_name: server3
    networks:
      - server-network

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: database
    logging:
      driver: none
    networks:
      - server-network

networks:
  server-network:
    driver: bridge
